# Generated by Django 5.2.6 on 2025-09-21 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_quantity',
            field=models.IntegerField(default=0, help_text='Total quantity sold', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
